### ISSUE TITLE
configurable "interesting keys" for monitor command

### ISSUE THREAD

**Issue by jboynyc** [schickling/beanstalkd-cli#3]
I mostly care about the number of jobs that are currently delayed. It would be nice if the "interesting keys" were configurable (short of editing the function and recompiling).

Thanks for providing this! Interesting to read a Rust project like this to learn about some of the language features.

**Comment by schickling** [comment]
That's a good idea! Please feel free to contribute this feature as a PR. I'd love to merge this.
